# Generated by Django 2.2.10 on 2020-03-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0013_deterministic_ordering'),
        ('dcim', '0099_powerfeed_negative_voltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('database', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('application_team', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('environnement', models.CharField(blank=True, max_length=50)),
                ('application_maintainer', models.CharField(blank=True, max_length=100, null=True)),
                ('profilepardefaut', models.CharField(blank=True, max_length=100, null=True)),
                ('actualprofile', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='dcim.Platform')),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='virtualization.VirtualMachine')),
            ],
            options={
                'ordering': ['name', 'slug', 'platform', 'database', 'virtual_machine', 'language', 'environnement', 'version', 'application_team', 'link', 'application_maintainer', 'profilepardefaut', 'actualprofile'],
            },
        ),
    ]
