# Generated by Django 2.2.10 on 2020-03-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0101_auto_20200304_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_version', models.CharField(blank=True, max_length=50)),
                ('recommended_version', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name', 'slug', 'language', 'actual_version', 'recommended_version'],
            },
        ),
    ]
