# Generated by Django 2.2.10 on 2020-03-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0013_deterministic_ordering'),
        ('dcim', '0103_auto_20200304_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderSystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name', 'slug', 'description'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name', 'slug', 'platform', 'application_type', 'undersystem', 'database', 'virtual_machine', 'language', 'environnement', 'version', 'application_team', 'link', 'application_maintainer', 'profilepardefaut', 'actualprofile']},
        ),
        migrations.CreateModel(
            name='UnderSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('version_minimum', models.CharField(max_length=100)),
                ('version_recommended', models.CharField(max_length=100)),
                ('database', models.CharField(blank=True, max_length=50)),
                ('end_of_support_minimum', models.DateField(null=True)),
                ('release_date_minimum', models.DateField(null=True)),
                ('end_of_support_recommended', models.DateField(null=True)),
                ('release_date_recommended', models.DateField(null=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_platform', to='dcim.Platform')),
                ('undersystem_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='undersystem_type', to='dcim.UnderSystemType')),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_machine', to='virtualization.VirtualMachine')),
            ],
            options={
                'ordering': ['name', 'slug', 'version_minimum', 'version_recommended', 'platform', 'undersystem_type', 'database', 'virtual_machine', 'release_date_minimum', 'end_of_support_minimum', 'release_date_recommended', 'end_of_support_recommended', 'language', 'version', 'comments'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='undersystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='undersystem', to='dcim.UnderSystem'),
        ),
    ]
