# Generated by Django 2.2.10 on 2020-03-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0104_auto_20200305_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name', 'slug', 'platform', 'application_type', 'virtual_machine', 'environnement', 'version', 'application_team', 'link', 'application_maintainer', 'scope', 'undersystem']},
        ),
        migrations.AlterModelOptions(
            name='applicationtype',
            options={'ordering': ['name', 'slug', 'language']},
        ),
        migrations.AlterModelOptions(
            name='undersystem',
            options={'ordering': ['name', 'slug', 'platform', 'undersystem_type', 'virtual_machine', 'version']},
        ),
        migrations.RemoveField(
            model_name='application',
            name='actualprofile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='database',
        ),
        migrations.RemoveField(
            model_name='application',
            name='language',
        ),
        migrations.RemoveField(
            model_name='application',
            name='profilepardefaut',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='actual_version',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='recommended_version',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='database',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='end_of_support_minimum',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='end_of_support_recommended',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='language',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='release_date_minimum',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='release_date_recommended',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='version_minimum',
        ),
        migrations.RemoveField(
            model_name='undersystem',
            name='version_recommended',
        ),
        migrations.AddField(
            model_name='application',
            name='scope',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
