# Generated by Django 2.2.10 on 2020-03-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_custom_tag_models'),
        ('dcim', '0105_auto_20200309_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name', 'slug', 'platform', 'application_type', 'virtual_machine', 'environnement', 'version', 'application_team', 'link', 'application_maintainer', 'scope', 'undersystem', 'status', 'tenant']},
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant', to='tenancy.Tenant'),
        ),
    ]
