# Generated by Django 2.2.10 on 2020-03-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0034_fix_ipaddress_status_dhcp'),
        ('dcim', '0106_auto_20200309_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name', 'slug', 'platform', 'application_type', 'virtual_machine', 'environnement', 'version', 'application_team', 'link', 'application_maintainer', 'scope', 'undersystem', 'status', 'tenant', 'ip_adress']},
        ),
        migrations.AddField(
            model_name='application',
            name='ip_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ip_adress', to='ipam.IPAddress'),
        ),
    ]
