# Generated by Django 2.2.10 on 2020-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0107_auto_20200309_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
